In [1]:
#import numpy library
import numpy as np

In [4]:
#first numpy array
first_numpy_array = np.array([1,2,3,4,5])

In [5]:
#print first array
print(first_numpy_array)

[1 2 3 4 5]


In [9]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[6.95325996e-310, 4.94065646e-324, 6.95325996e-310],
       [1.42173718e-312, 2.16939877e-317, 4.94065646e-324]])

In [15]:
#array with arange method
array_with_arrange = np.arange((12))
array_with_arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
#reshape method to create/change array
array_with_arrange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
#linspace for linearly (equal) spaced data elements
array_linspace = np.linspace(1,6,5)
array_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [20]:
#one dimensional array
oneD_array = np.arange((12))

In [21]:
#print one D array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
#two dimesional array
twoD_array = oneD_array.reshape(3,4)

In [23]:
#print two D array
print(twoD_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
#three dimensional array
threeD_array = np.arange((27)).reshape(3,3,3)

In [25]:
#print three D array
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [27]:
#ndim example : number of axes (dimensions) of the array
np_city = np.array(['Delhi','Mumbai','Chennai','Kolkata'])
np_city.ndim

1

In [28]:
#ndim example
np_city_with_state = np.array([['Delhi','Mumbai','Chennai','Kolkata'],['D','M','T','W']])
np_city_with_state.ndim

2

In [48]:
#calculate speed 
distance = ['30','40','50','60']
time = ['3','4','5','6']
np_dist = np.array(distance,dtype=np.int64)
np_time = np.array(time,dtype=np.int64)
speed = np_dist/np_time
speed

array([10., 10., 10., 10.])

In [36]:
#shape example : tuple of integers showing the size of the array in each dimension
np_city.shape

(4,)

In [37]:
#shape example
np_city_with_state.shape

(2, 4)

In [38]:
#size example :total number of elements in the array, equal to the product of the elements of the shape tuple
np_city.shape

(4,)

In [39]:
#size example
np_city_with_state.shape

(2, 4)

In [44]:
#dtype example : describes the type of the elements in the array
np_city.dtype
np_dist.dtype

dtype('int64')

In [45]:
#dtype example : describes the type of the elements in the array
np_city_with_state.dtype
np_time.dtype

dtype('int64')

In [46]:
#example addition
first = [10,20,30,40]
second = [50,60,70,80]
np_first = np.array(first)
np_second = np.array(second)
np_total = np_first + np_second
np_total

array([ 60,  80, 100, 120])