In [1]:
import numpy as np

In [2]:
#add
np.add(22,23)

45

In [3]:
#subtract
np.subtract(45,23)

22

In [7]:
#multiplication
np_daily_wages = np.array([7,8,6])*200
np_daily_wages

array([1400, 1600, 1200])

In [8]:
#total earning
sum(np_daily_wages)

4200

In [19]:
#comparison
np_weekly_hours = np.array(['42','36','30','24','18','12'],dtype=np.int64)
np_weekly_hours[np_weekly_hours>25]

array([42, 36, 30], dtype=int64)

In [20]:
#comparison
np_weekly_hours[np_weekly_hours!=24]

array([42, 36, 30, 18, 12], dtype=int64)

In [22]:
#logical AND operation
np.logical_and(np_weekly_hours>40,np_weekly_hours<50)

array([ True, False, False, False, False, False])

In [24]:
#logical not operation
np.logical_not(np_weekly_hours>=30)

array([False, False, False,  True,  True,  True])

In [25]:
#accessing array elements : indexing
cyclist_trials = np.array([[10,15,20,25],[12,14,16,18]])

In [26]:
#first trial data
first_trial = cyclist_trials[0]
first_trial

array([10, 15, 20, 25])

In [28]:
#second trial data
second_trial = cyclist_trials[1]
second_trial

array([12, 14, 16, 18])